language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - make lint test

jobs:
  include:
    - stage: deploy
      deploy:
        python: 3.7
        script: make docs
        provider: pages
        skip-cleanup: true
        local_dir: docs/build/html
        target_branch: gh-pages
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always