language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - make

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always