language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - make

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/build/html
  target_branch: gh-pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always