name: dejavu

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python: [3.7]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle --exclude=venv .
    - name: Test with pytest
      run: |
        pip install pytest
        python -m pytest test
    - name: Build and Deploy docs
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/build/html # The folder the action should deploy.
        BUILD_SCRIPT: cd docs; make html; cd build/html; touch .nojekyll
